### ISSUE TITLE
[suggestion] ImageRectOffset & ImageRectSize config for creating tabs

### ISSUE THREAD

**Issue by ActualMasterOogway** [biggaboy212/Maclib#1]
Allow us to set the ImageRectOffset and ImageRectSize for the icons so I can use [lucide roblox](https://github.com/latte-soft/lucide-roblox) with this lib

**Comment by biggaboy212** [comment]
Why not something like https://phosphoricons.com/?weight="fill" ?
You can download the assets and use the Roblox Studio "Asset Manager" to bulk upload

I'll add this but just saying Lucide isn't the right icon set for a Mac style design

**Comment by ActualMasterOogway** [comment]
> Why not something like https://phosphoricons.com/?weight="fill" ?
> You can download the assets and use the Roblox Studio "Asset Manager" to bulk upload
> 
> I'll add this but just saying Lucide isn't the right icon set for a Mac style design

Yeah, I put them on Roblox, and you were right, they don't look great.  Thanks for suggesting phosphoric icons they look awesome!
